apiVersion : apps/v1
kind: Deployment
metadata:
  name: rahulroyportcallopsprinter 
spec:
   selector:
     matchLabels:
       app: rahulroyportcallopsprinter
       version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: rahulroyportcallopsprinter 
    spec:
      containers:
        - name: rahulroyportcallopsprinter 
          image: royclouddemo.azurecr.io/rahulroyportcallopsprinter
          ports:
          - containerPort: 80