{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "portcallopsprinter-charts.serviceAccountName" . }}
  labels:
{{ include "portcallopsprinter-charts.labels" . | indent 4 }}
{{- end -}}
